### PR TITLE
PSR-3 Logging

### PR DESCRIPTION
**Pull request by Mark-H**
This is the second draft of the PSR-3 Logging Recommendation, first shared via Google Drive in October. Slightly updated text, however requires a bit more editing before putting it to a formal review/vote. Feedback is of course welcome.

### CODE REVIEW

**Comment by Mark-H** [comment]
This recommendation is now ready for formal review and vote as far as I'm concerned.

**Comment by Mark-H** [comment]
Started to play around a little bit with code for this. Getting this properly implemented will depending on the DIC (#12) as the logger and configuration for it should be retrieved from that (or a config file of sorts), but https://github.com/modxcms/revolution/compare/3.x...Mark-H:psr3?expand=1 is a functional implementation of PSR3/monolog into MODX 3, if anyone wants to give it a go.

**Comment by Jako** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by jpdevries** [comment]
👍

**Comment by Mark-H** [comment]
👍

**Comment by rthrash** [comment]
:+1:

**Comment by matdave** [comment]
👍

**Comment by rtripault** [comment]
:+1:

**Comment by mindeffects** [comment]
👍

**Comment by pmh1** [comment]
👍

**Comment by gpsietzema** [comment]
👍

**Comment by opengeek** [comment]
👍

**Pull request merged**
