### PR TITLE
Recommendation reference numbers

### PR DESCRIPTION
**Pull request by Mark-H**
This recommendation proposes a standardised way to number accepted recommendations and adds the steps needed by the (vice)chair. It is ready for review by the board.

### CODE REVIEW

**Comment by christianseel** [comment]
I remember we once talked about using the Github PR # as reference number. This seems easier, since already the PR would have an id.
Besides that, adding the IDs to filenames etc is an important step!

**Comment by Mark-H** [comment]
PR IDs aren't sequential though - some PRs might stay around for ages before the recommendation goes into vote (if at all), and rejected recommendations (or silly people like me sending non-recommendation pull requests) result in gaps in the references. 

Setting an incrementing number when it is accepted makes it so we have clear numbering from 1 to ??? where each number always refers to an accepted recommendation. There's also no question of MAB-15 was accepted before MAB-08 - because of the rules you instantly know 15 is more recent.

**Comment by gpsietzema** [comment]
Voting has started!

Only **MODX Board Members** may cast a vote. The **Chief Architect** and **Chief Maintainer** of the MODX Leadership are also granted one vote each. Votes may not be edited after they have been cast.

More info can be found in the [voting protocol](https://docs.google.com/document/d/1ZX5QBhIZNKnD3ammCzmEdR3uFlHXPo-nT4D9DUeaxkk).

**Comment by gpsietzema** [comment]
👍

**Comment by Jako** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by rtripault** [comment]
:+1:

**Comment by Mark-H** [comment]
👍

**Comment by rthrash** [comment]
👍

**Comment by jaygilmore** [comment]
👍

**Comment by matdave** [comment]
👍

**Comment by pmh1** [comment]
👍

**Comment by christianseel** [comment]
👍

**Pull request merged**
