### PR TITLE
Recommendation about CLI tool

### PR DESCRIPTION
**Pull request by rtripault**

### CODE REVIEW

**Comment by Mark-H** [comment]
I suppose this might be a question to the rest of the board as well, but how detailed do we want the recommendations to be? This recommendation mentions a lot of examples, but doesn't mention specifically what should be available in a MODX CLI tool. 

Personally I'm starting to think that it should be possible to assess (somewhat) objectively if a recommendation is implemented fully, for it to be most useful. I.e. it needs to have a clear path to action and completion.

For example [Jason's Slim 3 recommendation](https://github.com/modxcms/mab-recommendations/pull/10/files) is complete when MODX is refactored to be built on Slim 3 and [JPs Accessible Setup](https://github.com/modxcms/mab-recommendations/pull/14/files) is implemented when the setup provides accessibility options and an extra can register things to it. But when is this recommendation "done": if one item in the list of examples is implemented, or all of them? 

Or am I alone in looking for recommendations to be actionable with a finish line? If so I'm happy to adapt ;) Sorry if I'm being perhaps a bit too critical of the draft recommendations, just trying to figure out how we want to about things like this.

**Comment by jpdevries** [comment]
I ❤️ the idea of a CLI tool especially if it would let you update Extras (or whatever we call them now)



we could call it MPM 😆

**Comment by rtripault** [comment]
I'm not sure either how "generic" or technically agnostic we should be (the MAB is pretty new, let's allow some failure/trial ^^).

However, as a "technical guy", i would love them being some more closer to some kind of specs.

About this particular recommendation, i could consider it fulfilled if the following is "shipped" 

* `Developers should be able to ship their custom build commands (with their extras/components or independently)` (line 15)
* `install the CMS, upgrade the CMS, install components/extras` (line 18)

Also, keep in mind this is a draft, which, at least from my seat, is rather a request for comment(s) than anything else.

> Sorry if I'm being perhaps a bit too critical of the draft recommendations

Please don't (at least for mine), as you wrote, we need to figure out how we will work best (for ourselves, the product and the community)!

**Comment by jpdevries** [comment]
Not only is a CLI great for 🤓 power users but it is a great accessibility consideration for keyboard users! I try to "count the clicks" when creating interfaces. This could save _a ton_ of clicks.

**Comment by gpsietzema** [comment]
@rtripault Have you already done any coding for this? There is a working group at Sterc working on some own internal stuff for this, which might also come in handy for this recommendation and we don't want to write stuff which is already there.

**Comment by Jako** [comment]
@gpsietzema https://github.com/OptimusCrime/modx-cli has done some initial work on something similar. Maybe you could contact him. And this one exists https://github.com/meltingmedia/MODX-Shell

**Comment by rtripault** [comment]
After thinking a bit further about this, i believe the "core" should not provide such tool, leaving the room open for multiple players to develop their own CLI tools (the core team have enough work focusing only on the existing/upcoming core code).

Also, i never saw a single issue/feature request, so i would assume the Revo community does not really need such tool.

So closing this proposal

**Comment by matdave** [comment]
After looking into others and reading this I think that even if it's not "shipped" it would be a great asset to have something officially support that was also extensible.  It would be great to be able to tie in different automated processes using direct shell commands.

**Comment by rtripault** [comment]
> it would be a great asset to have something officially support that was also extensible

That was my idea too when writing this proposal. 

Turns out that the "officially supported" could rather be defined by the community (and adoption of such tool).
But to be fair, i think that's not the kind of tool our community is looking after.

**Pull request closed without merging**
