### PR TITLE
Replace 3rd Party Libraries in Core with Composer Dependencies

### PR DESCRIPTION
**Pull request by opengeek**
Only **MODX Board Members** may cast a vote. The **Chief Architect** and **Chief Maintainer** of the MODX Leadership are also granted one vote each. Votes may not be edited after they have been cast.

More info can be found in the [voting protocol](https://docs.google.com/document/d/1ZX5QBhIZNKnD3ammCzmEdR3uFlHXPo-nT4D9DUeaxkk).

### CODE REVIEW

**Comment by christianseel** [comment]
👍

**Comment by gpsietzema** [comment]
👍

**Comment by Jako** [comment]
👍

**Comment by Mark-H** [comment]
Yes please. 👍

**Comment by theboxer** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by opengeek** [comment]
👍

**Comment by rthrash** [comment]
👍 👍 👍 👍 👍

**Comment by sepiariver** [comment]
+1

**Comment by rtripault** [comment]
:+1:

**Comment by jpdevries** [comment]
👍

**Comment by pmh1** [comment]
👍

**Comment by matdave** [comment]
👍

**Comment by mindeffects** [comment]
👍

**Pull request merged**
