### PR TITLE
Refactor Data Model using xPDO 3.x

### PR DESCRIPTION
**Pull request by opengeek**
Only **MODX Board Members** may cast a vote. The **Chief Architect** and **Chief Maintainer** of the MODX Leadership are also granted one vote each. Votes may not be edited after they have been cast.

More info can be found in the [voting protocol](https://docs.google.com/document/d/1ZX5QBhIZNKnD3ammCzmEdR3uFlHXPo-nT4D9DUeaxkk).

### CODE REVIEW

**Comment by christianseel** [comment]
👍

**Comment by gpsietzema** [comment]
👍

**Comment by Jako** [comment]
👍

**Comment by Mark-H** [comment]
👍

**Comment by theboxer** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by opengeek** [comment]
👍

**Comment by rthrash** [comment]
👍

**Comment by sepiariver** [comment]
👍

**Comment by rtripault** [comment]
:+1:

**Comment by jpdevries** [comment]
👍

**Comment by pmh1** [comment]
👍

**Comment by matdave** [comment]
👍

**Comment by OptimusCrime** [comment]
If this gets accepted, as it looks like it will, does that mean xPDO 3.x will be "finished" in near future? Since the initial upgrade from 2.x to 3.x, it looks like there are a few things remaining.

* There are multiple pull requests that have been in a limbo state for a while not, with no feedback from maintainer(s).
* There are multiple proposed cache implementations that should either be rejected or included.
* Consider implementing a PostgreSQL OR. There is already a pull request for this and it would be awesome to support. 
* Consider using Travis or similar to build the package and running the tests. This would make it easier to differentiate errors from MODX and xPDO.
* There are a few issues that should be solved, like perhaps removing the pclzip lib, or at the very least fix the PHP7 fatal crash.
* Bump version to a stable one.

The official website it also somewhat confusing. A very obvious lacking menu item would be documentation, tutorial, get started or something similar. The footer has a link to documentation, but clearly states that it is for 2.x. Should MODX switch to 3.x, these things should be looked into, so developers are not left confused and have to go digging in the source code for clues.

**Comment by Mark-H** [comment]
@OptimusCrime Please don't raise your xPDO concerns/request features/report bugs in the middle of an unrelated vote*. 

(*To clarify why this is unrelated; this recommendation doesn't say MODX should adopt xPDO 3, it also doesn't say what xPDO 3 should look like. Instead this recommendation says that the model classes itself are to be refactored to xPDO 3 code instead of xPDO 2)

**Comment by mindeffects** [comment]
👍

**Pull request merged**
