### PR TITLE
Refactor MODX Revolution 3.x as Slim 3.x App

### PR DESCRIPTION
**Pull request by opengeek**
Only **MODX Board Members** may cast a vote. The **Chief Architect** and **Chief Maintainer** of the MODX Leadership are also granted one vote each. Votes may not be edited after they have been cast.

More info can be found in the [voting protocol](https://docs.google.com/document/d/1ZX5QBhIZNKnD3ammCzmEdR3uFlHXPo-nT4D9DUeaxkk).

### CODE REVIEW

**Comment by Mark-H** [comment]
I mentioned this on the trello board as well, but do the plans for Slim 4 there were published to github a few days ago impact this at all? Should we target 4 instead, or will that be a relatively straightforward upgrade once that stabilises in the future?

**Comment by opengeek** [comment]
Should be a straightforward upgrade from 3.x. Most of the 4.x work is to further decouple things like DI, which I am already replacing with PHP-DI. As 4.x work advances, it will become clearer if we need to target it, but I don't want to be waiting for a stable 4.x release of Slim while continuing this work.

**Comment by Mark-H** [comment]
Fair enough! :)

**Comment by christianseel** [comment]
👍

**Comment by Jako** [comment]
👍

**Comment by jpdevries** [comment]
👍

**Comment by gpsietzema** [comment]
👍

**Comment by Mark-H** [comment]
👍 Look forward to seeing the code ;)

**Comment by theboxer** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by opengeek** [comment]
👍

**Comment by rthrash** [comment]
👍

**Comment by sepiariver** [comment]
👍

**Comment by rtripault** [comment]
:+1:

**Comment by pmh1** [comment]
👍

**Comment by matdave** [comment]
👍

**Comment by mindeffects** [comment]
👍

**Pull request merged**
