### PR TITLE
MODX.org Recommendation

### PR DESCRIPTION
**Pull request by christianseel**
# MODX.org website

This is a MODX Advisory Board (MAB) recommendation for building a MODX.org website for the community and open source project.

* **Editors:** Christian Seel, Mark Hamstra, Gauke Pieter Sietzema, Romain Tripault, Rinze van der Brug, Mat Dave
* **First published draft:** 2017-04-18

### CODE REVIEW

**Comment by christianseel** [comment]
We are planing to start voting on this recommendation by April, 28th - if there is no feedback before we need to work on.

**Comment by christianseel** [comment]
# Voting has started!

**Only MODX Board Members may cast a vote**. The **Chief Architect** and **Chief Maintainer** of the MODX Leadership are also granted one vote each. Votes may not be edited after they have been cast.

More info can be found in the [voting protocol](https://docs.google.com/document/d/1ZX5QBhIZNKnD3ammCzmEdR3uFlHXPo-nT4D9DUeaxkk).

**Comment by christianseel** [comment]
👍

**Comment by gpsietzema** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by Jako** [comment]
👍

**Comment by jpdevries** [comment]
👍

**Comment by Mark-H** [comment]
:thumbsup:

**Comment by rtripault** [comment]
:+1:

**Comment by rthrash** [comment]
👍

**Comment by opengeek** [comment]
👍

**Comment by pmh1** [comment]
👍

**Comment by matdave** [comment]
👍

**Comment by Mark-H** [comment]
@gpsietzema @christianseel I think the vote should be called on this one ;)

**Comment by christianseel** [comment]
Recommendation accepted ✔️

**Pull request merged**
