### PR TITLE
RESTful API and moving away from ExtJS

### PR DESCRIPTION
**Pull request by Mark-H**
This is the second draft, slightly updated from the first version shared with the MAB in October via Google Drive.

### CODE REVIEW

**Comment by bezumkin** [comment]
Removing processors will also affect to custom resources classes.

And I just thought that with REST somebody will be able to provide a cloud-based "manager as a service". With strong security and lighting-fast bug fixes.

**Comment by OptimusCrime** [comment]
How will it affect custom resource classes? They can just provide similar REST endpoints as their connector counterparts.

Not sure what yo mean by cloud based manager service? Do you mean like hosting a manager that can access your MODX files?

**Comment by bezumkin** [comment]
> How will it affect custom resource classes?

CRC [requires base resource processors](https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-resource-classes/creating-a-resource-class/creating-a-resource-class-step-4). But, if there will no longer be a processors at all, we will need just to update CRC extras to use new extension technology. So, it is not a problem.

> Do you mean like hosting a manager that can access your MODX files?

Yes, it is just an idea. One global manager that will work with all your connected sites and manage them. All errors in one log with filters by site, all updates, news, etc.

**Comment by Mark-H** [comment]
Good one @bezumkin, I'll add that breaking change to the list.

**Comment by Jako** [comment]
It should not be a big deal to map REST endpoints that don't exist to processor files that exist to run the processor and return the result. Maybe there have to be two additional request parameter set for the REST endpoints (`namespace` -> to support extra processor folders, `result` -> to switch the result format - i.e. extjs for an object that could be handled by ExtJS). All ExtJS REST endpoints would be called by a GET request. If possible processor file locations are cached, the file location does not have to be scanned in every request.

**Comment by Mark-H** [comment]
Finished editing, now ready for formal review and vote.

**Comment by christianseel** [comment]
@Mark-H I guess
> Note: This recommendation is a DRAFT for consideration of the MODX Advisory Board.

needs to be removed before merging / now ( / always)?

**Comment by Mark-H** [comment]
Yes @christianseel, I'd suggest the person that merges it handles removing that during or immediately following the merge.

**Comment by Jako** [comment]
👍

**Comment by bezumkin** [comment]
👍

**Comment by jpdevries** [comment]
👍

**Comment by Mark-H** [comment]
👍

**Comment by rthrash** [comment]
👍

**Comment by matdave** [comment]
👍

**Comment by christianseel** [comment]
👍

**Comment by rtripault** [comment]
:+1:

**Comment by pmh1** [comment]
👍

**Comment by gpsietzema** [comment]
👍

**Comment by mindeffects** [comment]
👍

**Comment by opengeek** [comment]
👍

**Pull request merged**
